spring.application.name=MedicalProject
api.prefix=/api/v1

# ========== DataSource ==========
spring.datasource.url=${DB_URL}


# Користувач
spring.datasource.username=${DB_USER}


# Пароль
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# ========== JPA ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.connection.autocommit=false
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.dialect.storage_engine=default

# ========== Server (optional) ==========
server.port=8080

# ========== Logging ==========
logging.level.org.flywaydb=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.engine.jdbc.batch.internal=DEBUG
logging.level.org.hibernate.engine.jdbc.spi=DEBUG

# ========== Auth ==========
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=3600000
application.security.jwt.refresh-token.expiration=604800000

# stripe.api.key=${STRIPE_KEY}
# stripe.public.key=${STRIPE_PUBLIC_KEY}